services:
  - type: web
    name: app
    plan: free
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p static/output
    startCommand: gunicorn --workers 1 --timeout 120 --worker-class sync app:app
